addons:
  apt:
    packages:
        - expect-dev  # provides unbuffer utility
        - python-lxml # because pip installation is slow

language: python

python:
    - "2.7"

env:
    - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_advanced_reconcile_compassion,account_statement_completion_compassion"
  
virtualenv:
  system_site_packages: true

install:
    - pip install flake8
    - pip install pysftp
    - pip install MySQL-python
    - pip install unidecode 
    - pip install pysmb # allow to use "from smb.SMBConnection import SMBConnection"
    - pip install coveralls
    - pip install urllib3
    - pip install certifi
    - git clone https://github.com/CompassionCH/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b r2
    - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
    - git clone https://github.com/OCA/bank-statement-reconcile.git ${HOME}/build/CompassionCH/bank-statement-reconcile -b 8.0
    - git clone https://github.com/OCA/l10n-switzerland.git ${HOME}/build/CompassionCH/l10n-switzerland -b 8.0
    - git clone https://github.com/OCA/web.git ${HOME}/build/CompassionCH/web -b 8.0
    - git clone https://github.com/CompassionCH/compassion-modules.git ${HOME}/build/CompassionCH/compassion-modules -b 8.0
    - git clone https://github.com/OCA/bank-payment.git ${HOME}/build/CompassionCH/bank-payment -b 8.0
    - git clone https://github.com/OCA/account-financial-tools.git ${HOME}/build/CompassionCH/account-financial-tools -b 8.0
    - git clone https://github.com/CompassionCH/compassion-switzerland.git ${HOME}/build/CompassionCH/compassion-switzerland -b 8.0
    - git clone https://github.com/OCA/partner-contact.git ${HOME}/build/CompassionCH/partner-contact -b 8.0
    - git clone https://github.com/OCA/connector.git
    ${HOME}/build/CompassionCH/connector -b 8.0
    - travis_install_nightly

before_script:
    - touch ${HOME}/odoo-8.0/odoo.conf
  
script:
    - travis/travis_header.sh
    - travis_run_tests 


after_success:
    - coveralls
